In [172]:
import pandas as pd
import numpy as np

In [187]:
#Question1
data=pd.read_csv('neet_data.csv')
data.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [188]:
#Question2
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  object
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  object
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  object
 5   user_description     36510 non-null  object
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  object
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   object
 11  tweet                47381 non-null  object
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), object(7)
memory usage: 4.4+ MB

In [189]:
#Question3
data.sort_values(by='retweet_count',ascending=False,inplace=True)

In [190]:
#Question4
data.iloc[0,[2,6,7,4,11,0,10]]

source                                                Twitter for iPhone
user_follower_count                                                   62
user_friends_count                                                   115
user_name                           \xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3
tweet                  RT @JoeBiden: America, I\xe2\x80\x99m honored ...
created_at                                           2020-11-08 05:30:01
user_url                                         https://t.co/cHZdP4uOdu
Name: 32860, dtype: object

In [193]:
#Question5
count=data['retweet_count'].head(10).sum()
print('Top 10 Retweet sum is',count)

Top 10 Retweet sum is 2652225

In [194]:
#Question6
count=data[data['source']=='Twitter for Android']['retweet_count'].count()
print(count)
sum=data[data['source']=='Twitter for Android']['retweet_count'].sum()
print(sum)

28850
9386742

In [195]:
#Question7
data.sort_values(by='user_follower_count',ascending=False,inplace=True)
data.iloc[0,[4,8]]

user_name         NDTV
user_location    India
Name: 44367, dtype: object

In [196]:
#Question8
data['followers_friend_ratio']=data['user_follower_count']/data['user_friends_count']
data

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet,followers_friend_ratio
44367,2020-11-01 10:45:04,24,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"#Watch | In his 9th attempt, Arvind Kumar crac...",136,928957.000000
44424,2020-11-01 10:01:49,11,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My coaching centre supported me both ...",140,928957.000000
44355,2020-11-01 10:49:41,15,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,#Watch | Farmer's son Anil Kumar secures 77th ...,123,928957.000000
44436,2020-11-01 09:57:24,14,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My father is a farmer and my mother i...",133,928957.000000
23641,2020-10-30 08:58:00,2,Twitter Web App,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13901600,15,India,True,https://t.co/6yvEvvCmQi,Tamil Nadu Governor Clears 7.5% NEET Admission...,101,926773.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,0,Twitter Web App,1307231165506416640,sudhanshu jaiswal,I am a student,0,8,NaN,False,NaN,NEET 2020: Vectors - L - 6 | Class 11 | NEET P...,112,0.000000
9520,2020-10-28 14:00:49,175,Twitter Web App,1306828323058671616,SLR Legal Rights,NaN,0,23,NaN,False,NaN,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140,0.000000
30211,2020-10-28 14:00:49,175,Twitter Web App,1306828323058671616,SLR Legal Rights,NaN,0,23,NaN,False,NaN,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140,0.000000
23409,2020-10-30 09:59:50,0,Twitter for Android,1296322416218578944,Prateek Gupta,Student,0,10,"Uttar Pradesh, India",False,NaN,@DrRPNishank @narendramodi @AmitShah @PMOIndia...,131,0.000000
20778,2020-10-31 13:37:47,201,Twitter for Android,1312963204448948229,Chwayita,NaN,0,52,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.000000

In [197]:
#Question9
data.isnull().sum()

created_at                    0
retweet_count                 0
source                       19
user_id                       0
user_name                     1
user_description          10871
user_follower_count           0
user_friends_count            0
user_location             21134
user_verified                 0
user_url                  38101
tweet                         0
length_of_tweet               0
followers_friend_ratio      147
dtype: int64

In [198]:
#Question10
data['user_description'].fillna('Twitter User',inplace=True)
data

C:\Users\HP\AppData\Local\Temp\ipykernel_18140\3271653713.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['user_description'].fillna('Twitter User',inplace=True)

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet,followers_friend_ratio
44367,2020-11-01 10:45:04,24,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"#Watch | In his 9th attempt, Arvind Kumar crac...",136,928957.000000
44424,2020-11-01 10:01:49,11,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My coaching centre supported me both ...",140,928957.000000
44355,2020-11-01 10:49:41,15,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,#Watch | Farmer's son Anil Kumar secures 77th ...,123,928957.000000
44436,2020-11-01 09:57:24,14,Twitter Media Studio - LiveCut,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13934355,15,India,True,https://t.co/6yvEvvCmQi,"Watch | ""My father is a farmer and my mother i...",133,928957.000000
23641,2020-10-30 08:58:00,2,Twitter Web App,37034483,NDTV,Breaking news alerts from India.\n\nInstagram:...,13901600,15,India,True,https://t.co/6yvEvvCmQi,Tamil Nadu Governor Clears 7.5% NEET Admission...,101,926773.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,0,Twitter Web App,1307231165506416640,sudhanshu jaiswal,I am a student,0,8,NaN,False,NaN,NEET 2020: Vectors - L - 6 | Class 11 | NEET P...,112,0.000000
9520,2020-10-28 14:00:49,175,Twitter Web App,1306828323058671616,SLR Legal Rights,Twitter User,0,23,NaN,False,NaN,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140,0.000000
30211,2020-10-28 14:00:49,175,Twitter Web App,1306828323058671616,SLR Legal Rights,Twitter User,0,23,NaN,False,NaN,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140,0.000000
23409,2020-10-30 09:59:50,0,Twitter for Android,1296322416218578944,Prateek Gupta,Student,0,10,"Uttar Pradesh, India",False,NaN,@DrRPNishank @narendramodi @AmitShah @PMOIndia...,131,0.000000
20778,2020-10-31 13:37:47,201,Twitter for Android,1312963204448948229,Chwayita,Twitter User,0,52,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139,0.000000

In [199]:
#Question11
data.dropna(axis=1,inplace=True)
data

,created_at,retweet_count,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
44367,2020-11-01 10:45:04,24,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"#Watch | In his 9th attempt, Arvind Kumar crac...",136
44424,2020-11-01 10:01:49,11,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"Watch | ""My coaching centre supported me both ...",140
44355,2020-11-01 10:49:41,15,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,#Watch | Farmer's son Anil Kumar secures 77th ...,123
44436,2020-11-01 09:57:24,14,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"Watch | ""My father is a farmer and my mother i...",133
23641,2020-10-30 08:58:00,2,37034483,Breaking news alerts from India.\n\nInstagram:...,13901600,15,True,Tamil Nadu Governor Clears 7.5% NEET Admission...,101
...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,0,1307231165506416640,I am a student,0,8,False,NEET 2020: Vectors - L - 6 | Class 11 | NEET P...,112
9520,2020-10-28 14:00:49,175,1306828323058671616,Twitter User,0,23,False,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140
30211,2020-10-28 14:00:49,175,1306828323058671616,Twitter User,0,23,False,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140
23409,2020-10-30 09:59:50,0,1296322416218578944,Student,0,10,False,@DrRPNishank @narendramodi @AmitShah @PMOIndia...,131
20778,2020-10-31 13:37:47,201,1312963204448948229,Twitter User,0,52,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139

In [200]:
#Question12
data.insert(2,'is_allow',True)
data

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
44367,2020-11-01 10:45:04,24,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"#Watch | In his 9th attempt, Arvind Kumar crac...",136
44424,2020-11-01 10:01:49,11,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"Watch | ""My coaching centre supported me both ...",140
44355,2020-11-01 10:49:41,15,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,#Watch | Farmer's son Anil Kumar secures 77th ...,123
44436,2020-11-01 09:57:24,14,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,"Watch | ""My father is a farmer and my mother i...",133
23641,2020-10-30 08:58:00,2,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13901600,15,True,Tamil Nadu Governor Clears 7.5% NEET Admission...,101
...,...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,0,True,1307231165506416640,I am a student,0,8,False,NEET 2020: Vectors - L - 6 | Class 11 | NEET P...,112
9520,2020-10-28 14:00:49,175,True,1306828323058671616,Twitter User,0,23,False,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140
30211,2020-10-28 14:00:49,175,True,1306828323058671616,Twitter User,0,23,False,RT @AsianetNewsEN: [News Alert] #UttarPradesh ...,140
23409,2020-10-30 09:59:50,0,True,1296322416218578944,Student,0,10,False,@DrRPNishank @narendramodi @AmitShah @PMOIndia...,131
20778,2020-10-31 13:37:47,201,True,1312963204448948229,Twitter User,0,52,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139

In [201]:
#Question13
data.drop('tweet',axis=1,inplace=True)
data

,created_at,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,length_of_tweet
44367,2020-11-01 10:45:04,24,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,136
44424,2020-11-01 10:01:49,11,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,140
44355,2020-11-01 10:49:41,15,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,123
44436,2020-11-01 09:57:24,14,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,133
23641,2020-10-30 08:58:00,2,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13901600,15,True,101
...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,0,True,1307231165506416640,I am a student,0,8,False,112
9520,2020-10-28 14:00:49,175,True,1306828323058671616,Twitter User,0,23,False,140
30211,2020-10-28 14:00:49,175,True,1306828323058671616,Twitter User,0,23,False,140
23409,2020-10-30 09:59:50,0,True,1296322416218578944,Student,0,10,False,131
20778,2020-10-31 13:37:47,201,True,1312963204448948229,Twitter User,0,52,False,139

In [202]:
#Question14
data.insert(1,'created_year',data['created_at'].str.split('-').str[0])
data.insert(2,'created_month',data['created_at'].str.split('-').str[1])
data

,created_at,created_year,created_month,retweet_count,is_allow,user_id,user_description,user_follower_count,user_friends_count,user_verified,length_of_tweet
44367,2020-11-01 10:45:04,2020,11,24,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,136
44424,2020-11-01 10:01:49,2020,11,11,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,140
44355,2020-11-01 10:49:41,2020,11,15,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,123
44436,2020-11-01 09:57:24,2020,11,14,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13934355,15,True,133
23641,2020-10-30 08:58:00,2020,10,2,True,37034483,Breaking news alerts from India.\n\nInstagram:...,13901600,15,True,101
...,...,...,...,...,...,...,...,...,...,...,...
14011,2020-10-26 17:37:27,2020,10,0,True,1307231165506416640,I am a student,0,8,False,112
9520,2020-10-28 14:00:49,2020,10,175,True,1306828323058671616,Twitter User,0,23,False,140
30211,2020-10-28 14:00:49,2020,10,175,True,1306828323058671616,Twitter User,0,23,False,140
23409,2020-10-30 09:59:50,2020,10,0,True,1296322416218578944,Student,0,10,False,131
20778,2020-10-31 13:37:47,2020,10,201,True,1312963204448948229,Twitter User,0,52,False,139